### ISSUE TITLE
Template Function

### ISSUE THREAD

**Issue by sir-andreas** [knowthelist/ftui#19]
Hi all, 
is there a similar function included like "data-template" in FTUI2? 
(see https://wiki.fhem.de/wiki/FHEM_Tablet_UI#Templates)

Best regards,
Andreas

**Comment by knowthelist** [comment]
Yes, you could use. <ftui-content> 

Load content from a (template) file 
`
<ftui-content file="examples/contents/content-view2.html" room="Room2"></ftui-content>
`

Load content from a FHEM reading

`<ftui-content [content]="ftuitest:html"></ftui-content>`

See: https://github.com/knowthelist/ftui/blob/master/www/ftui/examples/content.html
and
https://github.com/knowthelist/ftui/blob/master/www/ftui/examples/content2.html
