### ISSUE TITLE
ftui.helper.js: extend/replace dateFormat to regard more languages properly

### ISSUE THREAD

**Issue by y3rs1n14** [knowthelist/ftui#53]
Can you extend/replace [dateFormat function](https://github.com/knowthelist/ftui/blob/master/www/ftui/modules/ftui/ftui.helper.js#L224) in ftui.helper.js with [DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat) or [toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)?
This might be a smart way to get more international names (for months and weekday), abbreviations and time formats.

**Comment by knowthelist** [comment]
I think the implementation would be quite complicated due to the lot of options. But it is very easy to use this on your own page as a pipe function

```
<script>
  const myDateTimeFormat1 = () => value => new Intl.DateTimeFormat('it', {weekday: "long"}).format(value);
  const myDateTimeFormat2 = () => value => new Intl.DateTimeFormat('it', {weekday: "short"}).format(value);
</script>

<ftui-label [text]="AgroWeather:state:time | toDate() | myDateTimeFormat1()"></ftui-label>
<ftui-label [text]="AgroWeather:state:time | toDate() | myDateTimeFormat2()"></ftui-label>
   
```
